[package]
name = "scitool"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
bitter = "0.7.0"
clap = { version = "4.5.16", features = ["derive"] }
hxdmp = "0.2.1"
itertools = "0.13.0"
maud = "0.26.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yml = "0.0.12"
thiserror = "1.0.63"
unicode-properties = "0.1.2"

[workspace]
members = ["crates/*"]
